# Generated by Django 5.2.8 on 2025-11-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('unique_op_id', models.AutoField(db_column='UniqueOpID', primary_key=True, serialize=False)),
                ('bid_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('WON', 'Won'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], db_column='BidStatus', max_length=50)),
                ('bid_type', models.CharField(choices=[('NEW', 'New'), ('RENEWAL', 'Renewal'), ('EXTENSION', 'Extension')], db_column='BidType', max_length=50)),
                ('region_id', models.CharField(db_column='RegionID', max_length=100)),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'db_table': 'opportunities',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(db_column='ClientID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('country_id', models.AutoField(db_column='CountryID', primary_key=True, serialize=False)),
                ('region_id', models.CharField(db_column='RegionID', max_length=100)),
                ('country_name', models.CharField(db_column='CountryName', max_length=255)),
                ('water_depth_min', models.DecimalField(blank=True, db_column='WaterDepthMin', decimal_places=2, max_digits=10, null=True)),
                ('water_depth_max', models.DecimalField(blank=True, db_column='WaterDepthMax', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='BidMetrics',
            fields=[
                ('opportunity', models.OneToOneField(db_column='OpportunityID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bid_metrics', serialize=False, to='market_analysis.opportunity')),
                ('ebit', models.DecimalField(blank=True, db_column='EBIT', decimal_places=2, max_digits=15, null=True)),
                ('gp', models.DecimalField(blank=True, db_column='GP', decimal_places=2, max_digits=15, null=True)),
                ('gm', models.DecimalField(blank=True, db_column='GM', decimal_places=2, help_text='Gross Margin %', max_digits=5, null=True)),
                ('revenue', models.DecimalField(blank=True, db_column='Revenue', decimal_places=2, max_digits=15, null=True)),
                ('cash_cost', models.DecimalField(blank=True, db_column='CashCost', decimal_places=2, max_digits=15, null=True)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', help_text='Duration in days', null=True)),
                ('option', models.CharField(blank=True, db_column='Option', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Bid Metric',
                'verbose_name_plural': 'Bid Metrics',
                'db_table': 'bid_metrics',
            },
        ),
        migrations.CreateModel(
            name='CycleTime',
            fields=[
                ('opportunity', models.OneToOneField(db_column='OpportunityID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cycle_times', serialize=False, to='market_analysis.opportunity')),
                ('rec_to_submission', models.IntegerField(blank=True, db_column='RectoSubmission', help_text='Days from receipt to submission', null=True)),
                ('submission_to_award', models.IntegerField(blank=True, db_column='SubmissionToAward', help_text='Days from submission to award', null=True)),
                ('award_to_start', models.IntegerField(blank=True, db_column='AwardToStart', help_text='Days from award to start', null=True)),
                ('total_cycle', models.IntegerField(blank=True, db_column='TotalCycle', help_text='Total cycle time in days', null=True)),
            ],
            options={
                'verbose_name': 'Cycle Time',
                'verbose_name_plural': 'Cycle Times',
                'db_table': 'cycle_times',
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='client',
            field=models.ForeignKey(db_column='ClientID', on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='market_analysis.client'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node_type', models.CharField(db_column='NodeType', max_length=100)),
                ('node_qty', models.IntegerField(db_column='NodeQty')),
                ('vessel_name', models.CharField(blank=True, db_column='VesselName', max_length=255, null=True)),
                ('nhv_qty', models.IntegerField(blank=True, db_column='NHVQty', help_text='NHV Quantity', null=True)),
                ('sv_qty', models.IntegerField(blank=True, db_column='SVQty', help_text='SV Quantity', null=True)),
                ('opportunity', models.ForeignKey(db_column='OpportunityID', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='market_analysis.opportunity')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'db_table': 'equipment',
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='country',
            field=models.ForeignKey(db_column='CountryID', on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='market_analysis.location'),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_received', models.DateField(blank=True, db_column='DateReceived', null=True)),
                ('date_deadline', models.DateField(blank=True, db_column='DateDeadline', null=True)),
                ('date_award', models.DateField(blank=True, db_column='DateAward', null=True)),
                ('date_contract', models.DateField(blank=True, db_column='DateContract', null=True)),
                ('actual_start', models.DateField(blank=True, db_column='ActualStart', null=True)),
                ('actual_end', models.DateField(blank=True, db_column='ActualEnd', null=True)),
                ('opportunity', models.OneToOneField(db_column='OpportunityID', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='market_analysis.opportunity')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'db_table': 'milestones',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(db_column='ProjectID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('region_id', models.CharField(db_column='RegionID', max_length=100)),
                ('country', models.ForeignKey(db_column='CountryID', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='market_analysis.location')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='project',
            field=models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='market_analysis.project'),
        ),
    ]
