# Generated by Django 5.2.8 on 2025-11-19 16:23

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycletime',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='opportunity',
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=django_countries.fields.CountryField(db_column='Country', max_length=2),
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='country',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='client',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='region_id',
        ),
        migrations.AddField(
            model_name='project',
            name='bid_type',
            field=models.CharField(choices=[('RFQ', 'Request for Quotation'), ('RFP', 'Request for Proposal'), ('RFI', 'Request for Information'), ('MC', 'Multi-Client'), ('DR', 'Direct Award'), ('BQ', 'Budgetary Quotation')], db_column='BidType', default='BQ', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, db_column='ClientID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='market_analysis.client'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_received',
            field=models.DateField(blank=True, db_column='DateReceived', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='internal_id',
            field=models.CharField(blank=True, db_column='InternalID', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, choices=[('NA', 'North America'), ('APAC', 'Asia Pacific'), ('ME', 'Middle East'), ('SA', 'South America'), ('AAME', 'Africa and Middle East'), ('WAF', 'West Africa'), ('NWE', 'North West Europe')], db_column='Region', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Submitted', 'Submitted'), ('Won', 'Won'), ('Lost', 'Lost'), ('Cancelled', 'Cancelled')], db_column='Status', default='Ongoing', max_length=10),
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
        migrations.CreateModel(
            name='BidTypeHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_bid_type', models.CharField(blank=True, choices=[('RFQ', 'Request for Quotation'), ('RFP', 'Request for Proposal'), ('RFI', 'Request for Information'), ('MC', 'Multi-Client'), ('DR', 'Direct Award'), ('BQ', 'Budgetary Quotation')], max_length=10, null=True)),
                ('new_bid_type', models.CharField(choices=[('RFQ', 'Request for Quotation'), ('RFP', 'Request for Proposal'), ('RFI', 'Request for Information'), ('MC', 'Multi-Client'), ('DR', 'Direct Award'), ('BQ', 'Budgetary Quotation')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, related_name='bid_history', to='market_analysis.project')),
            ],
            options={
                'verbose_name': 'Bid Type History',
                'verbose_name_plural': 'Bid Type Histories',
                'db_table': 'bid_type_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ebit_day', models.DecimalField(blank=True, db_column='EBIT/Day', decimal_places=2, max_digits=15, null=True)),
                ('gp', models.DecimalField(blank=True, db_column='GP', decimal_places=2, max_digits=15, null=True)),
                ('gm', models.DecimalField(blank=True, db_column='GM', decimal_places=2, help_text='Gross Margin %', max_digits=5, null=True)),
                ('revenue', models.DecimalField(blank=True, db_column='Revenue', decimal_places=2, max_digits=15, null=True)),
                ('cash_cost', models.DecimalField(blank=True, db_column='CashCost', decimal_places=2, max_digits=15, null=True)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', help_text='Duration in days', null=True)),
                ('project', models.OneToOneField(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='market_analysis.project')),
            ],
            options={
                'verbose_name': 'Financial',
                'verbose_name_plural': 'Financials',
                'db_table': 'financials',
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('technology', models.CharField(choices=[('STR', 'Streamer'), ('OBN', 'Ocean Bottom Node'), ('OTHER', 'Other')], db_column='Technologies', max_length=50)),
                ('survey_type', models.CharField(choices=[('2D Seismic', '2D Seismic'), ('3D Seismic', '3D Seismic'), ('4D Seismic', '4D Seismic'), ('GM', 'Gravity & Magnetics'), ('NES', 'New Energy Solutions')], db_column='SurveyType', max_length=50)),
                ('obn_technique', models.CharField(blank=True, choices=[('NOAR', 'Node on a Rope'), ('ROV', 'Remotely Operated Vehicle Deployed Nodes')], db_column='OBNTechnique', max_length=50, null=True)),
                ('obn_type', models.CharField(blank=True, choices=[('ZXPLR', 'ZXPLORE'), ('Z700', 'Z700'), ('MASS', 'MASS'), ('OTHER', 'Other')], db_column='OBNSystem', max_length=50, null=True)),
                ('streamer', models.CharField(blank=True, choices=[('CONV', 'Conventional'), ('DUAL', 'Dual Sensor'), ('GSTRM', 'GeoStreamer')], db_column='Streamer', max_length=50, null=True)),
                ('project', models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='market_analysis.project')),
            ],
            options={
                'verbose_name': 'Project Technology',
                'verbose_name_plural': 'Project Technologies',
                'db_table': 'project_technologies',
            },
        ),
        migrations.DeleteModel(
            name='BidMetrics',
        ),
        migrations.DeleteModel(
            name='CycleTime',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
    ]
