# Generated by Django 5.2.8 on 2025-11-19 19:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0002_remove_cycletime_opportunity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='duration',
            new_name='duration_raw',
        ),
        migrations.RemoveField(
            model_name='financial',
            name='cash_cost',
        ),
        migrations.RemoveField(
            model_name='financial',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='projecttechnology',
            name='obn_type',
        ),
        migrations.AddField(
            model_name='financial',
            name='depreciation',
            field=models.DecimalField(blank=True, db_column='Depreciation', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='duration_with_dt',
            field=models.IntegerField(blank=True, db_column='Duration_w_dt', help_text='Duration with downtime in days', null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='ebit_amount',
            field=models.DecimalField(blank=True, db_column='EBIT', decimal_places=2, help_text='EBIT in $', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='ebit_pct',
            field=models.DecimalField(blank=True, db_column='EBIT_PCT', decimal_places=2, help_text='EBIT in %', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='ebitda_amount',
            field=models.DecimalField(blank=True, db_column='EBITDA_USD', decimal_places=2, help_text='EBITDA in $', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='ebitda_pct',
            field=models.DecimalField(blank=True, db_column='EBITDA_PCT', decimal_places=2, help_text='EBITDA in %', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='file_upload_TMA',
            field=models.FileField(blank=True, db_column='FileUpload_TMA', null=True, upload_to='financial_uploads/'),
        ),
        migrations.AddField(
            model_name='financial',
            name='net_amount',
            field=models.DecimalField(blank=True, db_column='NET_USD', decimal_places=2, help_text='Net Income $', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='net_day',
            field=models.DecimalField(blank=True, db_column='NET_PER_DAY', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='net_pct',
            field=models.DecimalField(blank=True, db_column='NET_PCT', decimal_places=2, help_text='Net Income %', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='overhead_dayrate',
            field=models.DecimalField(blank=True, db_column='OVERHEAD_DAYRATE', decimal_places=2, default=Decimal('21000.00'), editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='financial',
            name='taxes',
            field=models.DecimalField(blank=True, db_column='Taxes', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='total_direct_cost',
            field=models.DecimalField(blank=True, db_column='Cost', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='total_overhead',
            field=models.DecimalField(blank=True, db_column='TotalOverhead', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='total_revenue',
            field=models.DecimalField(blank=True, db_column='TotalRevenue', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_portal_id',
            field=models.CharField(blank=True, db_column='ProjectPortalID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projecttechnology',
            name='obn_system',
            field=models.CharField(blank=True, choices=[('ZXPLR', 'ZXPLORE'), ('Z700', 'Z700'), ('MASS', 'MASS'), ('GPR300', 'GPR300'), ('OTHER', 'Other')], db_column='OBNSystem', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='ebit_day',
            field=models.DecimalField(blank=True, db_column='EBIT_PER_DAY', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='gm',
            field=models.DecimalField(blank=True, db_column='GM', decimal_places=2, help_text='Gross Margin %', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='gp',
            field=models.DecimalField(blank=True, db_column='GP', decimal_places=2, help_text='Gross Profit $', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, choices=[('NA', 'North America'), ('APAC', 'Asia Pacific'), ('SA', 'South America'), ('AAME', 'Africa and Middle East'), ('WAF', 'West Africa'), ('NWE', 'North West Europe')], db_column='Region', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Submitted', 'Submitted'), ('Won', 'Won'), ('Lost', 'Lost'), ('Cancelled', 'Cancelled'), ('No Bid', 'No Bid')], db_column='Status', default='Ongoing', max_length=10),
        ),
        migrations.AlterField(
            model_name='projecttechnology',
            name='obn_technique',
            field=models.CharField(blank=True, choices=[('NOAR', 'Node on a Rope'), ('ROV', 'Remotely Operated Vehicle Deployed Nodes'), ('DN', 'Drop Nodes')], db_column='OBNTechnique', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projecttechnology',
            name='survey_type',
            field=models.CharField(choices=[('2D Seismic', '2D Seismic'), ('3D Seismic', '3D Seismic'), ('4D Seismic', '4D Seismic'), ('GM', 'Gravity & Magnetics'), ('NES', 'New Energy Solutions'), ('HYBD', 'Hybrid')], db_column='SurveyType', max_length=50),
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
