# Generated by Django 5.2.8 on 2025-11-19 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0003_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='award_date',
            field=models.DateField(blank=True, db_column='AwardDate', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lost_date',
            field=models.DateField(blank=True, db_column='LostDate', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='submission_date',
            field=models.DateField(blank=True, db_column='SubmissionDate', null=True),
        ),
        migrations.CreateModel(
            name='ProjectContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_date', models.DateField(blank=True, db_column='ContractDate', null=True)),
                ('actual_start', models.DateField(blank=True, db_column='ActualStart', null=True)),
                ('actual_end', models.DateField(blank=True, db_column='ActualEnd', null=True)),
                ('actual_duration', models.IntegerField(blank=True, db_column='ActualDuration', help_text='Duration (days) derived from start/end', null=True)),
                ('project', models.OneToOneField(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='market_analysis.project')),
            ],
            options={
                'verbose_name': 'Project Contract',
                'verbose_name_plural': 'Project Contracts',
                'db_table': 'project_contracts',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='market_analysis.project')),
            ],
            options={
                'verbose_name': 'Project Status History',
                'verbose_name_plural': 'Project Status Histories',
                'db_table': 'project_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
