# Generated by Django 5.2.8 on 2025-11-19 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0004_project_award_date_project_lost_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('STATUS', 'Status change'), ('BID', 'Bid type change'), ('OTHER', 'Other')], max_length=16)),
                ('field_name', models.CharField(max_length=50)),
                ('previous_value', models.CharField(blank=True, max_length=200, null=True)),
                ('new_value', models.CharField(blank=True, max_length=200, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='market_analysis.project')),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'db_table': 'change_log',
                'ordering': ['-changed_at'],
            },
        ),
    ]
