# Generated by Django 5.2.8 on 2025-11-20 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0005_changelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('BID', 'Bid type change'), ('STATUS', 'Status change'), ('OTHER', 'Other')], max_length=16)),
                ('snapshot', models.JSONField()),
                ('snapshot_name', models.CharField(blank=True, help_text='Previous internal_id or name', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='market_analysis.project')),
            ],
            options={
                'verbose_name': 'Project Snapshot',
                'verbose_name_plural': 'Project Snapshots',
                'db_table': 'project_snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
