# Generated by Django 5.2.8 on 2025-11-20 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0006_projectsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='market_analysis.project')),
            ],
            options={
                'verbose_name': 'Competitor',
                'verbose_name_plural': 'Competitors',
                'db_table': 'competitors',
                'ordering': ['-created_at'],
            },
        ),
    ]
