# Generated by Django 5.2.8 on 2025-11-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0007_competitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='name',
            field=models.CharField(blank=True, choices=[('SAE', 'SAE'), ('PXGEO', 'PXGEO'), ('VIRIDIEN', 'Viridien'), ('SLB', 'SLB'), ('SHEARWATER', 'Shearwater'), ('BGP', 'BGP'), ('COSL', 'COSL')], db_column='Name', max_length=50, null=True),
        ),
    ]
