# Generated by Django 5.2.8 on 2025-11-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0008_alter_competitor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, choices=[('NSA', 'NSA'), ('Asia', 'Asia'), ('Asia', 'Asia'), ('Australasia', 'Australasia'), ('Europe', 'Europe'), ('Global', 'Global')], db_column='Region', max_length=12, null=True),
        ),
    ]
