# Generated by Django 5.2.8 on 2025-11-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0010_alter_project_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttechnology',
            name='obn_system',
            field=models.CharField(blank=True, choices=[('ZXPLR', 'ZXPLR'), ('Z700', 'Z700'), ('MASS', 'MASS'), ('GPR300', 'GPR300'), ('OTHER', 'Other')], db_column='OBNSystem', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projecttechnology',
            name='obn_technique',
            field=models.CharField(blank=True, choices=[('NOAR', 'NOAR'), ('ROV', 'ROV'), ('DN', 'DN')], db_column='OBNTechnique', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projecttechnology',
            name='technology',
            field=models.CharField(choices=[('STR', 'Streamer'), ('OBN', 'OBN'), ('OTHER', 'Other')], db_column='Technologies', max_length=50),
        ),
    ]
