# Generated by Django 5.2.8 on 2025-11-24 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0011_alter_projecttechnology_obn_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeOfWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_rx_locs', models.IntegerField(blank=True, db_column='TotalRxLocs', null=True)),
                ('total_sx_locs', models.IntegerField(blank=True, db_column='TotalSxLocs', null=True)),
                ('max_active_spread', models.IntegerField(blank=True, db_column='MaxActiveSpread', null=True)),
                ('crew_node_count', models.IntegerField(blank=True, db_column='CrewNodeCount', null=True)),
                ('node_area', models.IntegerField(blank=True, db_column='NodeArea', null=True)),
                ('source_area', models.IntegerField(blank=True, db_column='SourceArea', null=True)),
                ('node_grid_IL', models.IntegerField(blank=True, db_column='NodeGridIL', null=True)),
                ('node_grid_XL', models.IntegerField(blank=True, db_column='NodeGridXL', null=True)),
                ('source_grid_IL', models.IntegerField(blank=True, db_column='SourceGridIL', null=True)),
                ('source_grid_XL', models.IntegerField(blank=True, db_column='SourceGridXL', null=True)),
                ('water_depth_min', models.IntegerField(blank=True, db_column='WaterDepth', null=True)),
                ('water_depth_max', models.IntegerField(blank=True, db_column='WaterDepthMax', null=True)),
                ('node_category', models.CharField(blank=True, choices=[('Shallow Water', 'Shallow Water'), ('Deep Water', 'Deep Water')], db_column='NodeCategory', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, related_name='scopes_of_work', to='market_analysis.project')),
            ],
            options={
                'verbose_name': 'Scope of Work',
                'verbose_name_plural': 'Scopes of Work',
                'db_table': 'scope_of_work',
                'ordering': ['-created_at'],
            },
        ),
    ]
