# Generated by Django 5.2.8 on 2025-12-01 19:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0012_scopeofwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='overhead_dayrate',
            field=models.DecimalField(blank=True, db_column='OVERHEAD_DAYRATE', decimal_places=2, default=Decimal('21000.00'), max_digits=15),
        ),
    ]
