# Generated by Django 5.2.8 on 2025-11-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0012_scopeofwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, choices=[('NSA', 'NSA'), ('AMME', 'AMME'), ('Asia', 'Asia'), ('Australasia', 'Australasia'), ('Europe', 'Europe'), ('Global', 'Global'), ('WAF', 'WAF')], db_column='Region', max_length=12, null=True),
        ),
    ]
