# Generated by Django 5.2.8 on 2025-12-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0013_alter_financial_overhead_dayrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.TextField(blank=True, db_column='Comments', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline_date',
            field=models.DateField(blank=True, db_column='DeadlineDate', null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='duration_raw',
            field=models.DecimalField(blank=True, db_column='Duration', decimal_places=2, help_text='Duration in days', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='duration_with_dt',
            field=models.DecimalField(blank=True, db_column='Duration_w_dt', decimal_places=2, help_text='Duration with downtime in days', max_digits=7, null=True),
        ),
    ]
