# Generated by Django 5.2.8 on 2025-12-04 18:41

import django.core.validators
import market_analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0014_add_deadline_and_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_map',
            field=models.ImageField(blank=True, db_column='ProjectMap', help_text='Upload a project map image (PNG, JPG, GIF). Max size: 5 MB.', null=True, upload_to='project_maps/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), market_analysis.models.validate_image_file_size]),
        ),
    ]
